def call_mock_llm(prompt: str, query: str) -> str:
    return f"""
🤖 Mock AI Response

System Prompt:
{prompt}

User Question:
{query}

Explanation:
This is a simulated AI response for demo and testing purposes.
In a real deployment, this would be generated by an LLM.
"""






